# Generated by Django 6.0.5 on 2026-05-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SariItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rice_grains', 'Rice & Grains'), ('canned_goods', 'Canned Goods'), ('condiments', 'Condiments & Sauces'), ('noodles_pasta', 'Noodles & Pasta'), ('snacks', 'Snacks & Chips'), ('biscuits', 'Biscuits & Cookies'), ('candy', 'Candy & Sweets'), ('chocolate', 'Chocolate'), ('bread_bakery', 'Bread & Bakery'), ('beverage_hot', 'Coffee & Tea'), ('beverage_cold', 'Juice & Soft Drinks'), ('water', 'Water & Ice'), ('dairy', 'Dairy & Eggs'), ('frozen', 'Frozen Goods'), ('household', 'Household Supplies'), ('cleaning', 'Cleaning Products'), ('personal', 'Personal Care'), ('medicine', 'Medicine & Essentials'), ('school', 'School Supplies'), ('tobacco', 'Tobacco & Lighter'), ('load', 'Load & E-Wallet'), ('other', 'Other')], default='other', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='piece', max_length=50)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Stock Added'), ('remove', 'Stock Removed'), ('adjust', 'Manual Adjustment')], max_length=10)),
                ('quantity_changed', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.sariitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
