# Generated by Django 6.0.5 on 2026-05-26 04:10

import django.db.models.deletion
import watches.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/')),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('used', 'Pre-owned'), ('restored', 'Restored / Cleaned'), ('limited', 'Limited Edition')], default='new', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=watches.models._generate_order_id, editable=False, max_length=20, unique=True)),
                ('payment_method', models.CharField(choices=[('gcash', 'GCash'), ('shop', 'Pay at Shop')], max_length=10)),
                ('delivery_option', models.CharField(choices=[('pickup', 'Pick up at Store'), ('delivery', 'Home Delivery')], max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gcash_screenshot', models.ImageField(blank=True, null=True, upload_to='gcash/')),
                ('gcash_ref_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('watch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='watches.watchitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
